= AsciiDoc 写作指南
:toc: auto
:imagesdir: images
:doctype: book
:toclevels: 3

本指南简要介绍了 AsciiDoc，一种纯文本文档语法和处理器。本简介适用于希望减少编写和发布内容所需工作量的任何人，无论是技术文档、文章、网页还是优秀的老式散文。

TIP: 如果你想了解 AsciiDoc 是怎么回事，请在link:https://docs.asciidoctor.org/asciidoc/latest/#about-asciidoc[关于 AsciiDoc] 中寻找答案。如果你正在寻找 AsciiDoc 语法的简明概览，请参阅 link:0-syntax-quick-ref.adoc[《AsciiDoc 语法快速参考》]。

在本指南中，你将了解：

* AsciiDoc 文档的基本结构
* 如何创建你的第一个 AsciiDoc 文档
* 如何添加其他结构元素，例如列表、块引用和源代码
* 如何将 AsciiDoc 文档转换为 HTML、DocBook 和 PDF

除了涵盖 AsciiDoc 基础知识之外，本指南还建议了一组约定，以帮助你创建更一致的文档并最大限度地提高你的写作效率。

让我们深入了解 AsciiDoc 吧！

== 用 AsciiDoc 写作

本节的目标是教你如何编写你的第一个 AsciiDoc 文档。希望当你回头看时，你会同意这是有意义的。

你与 AsciiDoc 冒险始于你最喜欢的文本编辑器。

=== 它只是文本，伙计。

由于 AsciiDoc 语法只是纯文本，你可以使用任何文本编辑器编写 AsciiDoc 文档。你不需要复杂的文字处理程序，如 Microsoft Word、OpenOffice Writer 或 Google Docs。事实上，你不应该使用这些程序，因为它们会给你的文档增加（你看不到的）麻烦并使转换变得乏味。

TIP: 虽然任何文本编辑器都可以，但我建议选择一个支持 AsciiDoc 语法高亮的编辑器。颜色给文本带来对比，使其更容易阅读。高亮显示还可以确认你为内联或块元素输入了正确的语法。

在 macOS 上编辑纯文本最流行的应用程序是 **TextMate**。Linux 上类似的选择是 **GEdit**。在 Windows 上，请远离记事本footnote:[https://en.wikipedia.org/wiki/Windows_Notepad]和写字板footnote:[https://en.wikipedia.org/wiki/WordPad]，因为它们生成的纯文本对跨平台不友好。你可以选择像 **link:https://kate-editor.org/[Kate]** 这样的功能强大的文本编辑器。如果你是一名程序员（或追求极客的作家），你可能会更喜欢 **Vim**、**Emacs**、**VS Code** 或 **Sublime Text**，它们都可以跨平台使用。所有这些编辑器共有的关键特性是 AsciiDoc 的语法高亮显示。

打开你最喜欢的文本编辑器，准备好写一些 AsciiDoc！

=== 内容为王！

文档中的大部分内容是段落文本。这就是 Asciidoctor 不需要任何特殊标记或属性来指定段落内容的原因。你可以直接开始打字了。

在 Asciidoctor 中，相邻或连续的文本行构成一个段落元素。要在另一个元素（例如章节标题或表格）之后开始一个新段落，请按两次 `Enter` 键以插入一个空行，然后继续输入内容。

.AsciiDoc 文档中的两个段落
====
 这是第一段的第一句。
 这是第一段的第二局。

 这是第二段的第一句。
====

.使用默认 (html5) 转换器和样式表 (asciidoctor.css) 呈现的两个段落
====
这是第一段的第一句。
这是第一段的第二局。

这是第二段的第一句。
====

就这样，**你正在用 AsciiDoc 写作！**如你所见，这就像写一封电子邮件。

使用文件扩展名 `.adoc` 保存文件。

TIP: 如果您想了解如何将文档转换为 HTML、DocBook 或 PDF，请向前跳至<<converting-your-document,转换文档>>部分。

==== 换行文本和硬换行

TIP: 由于中文与英文的书写习惯不同，并不建议采用将不同的句子分配到不同的行，让 AsciiDoctor 自动解析的做法。

由于当 Asciidoctor 转换文档时，相邻的文本行被组合成一个段落，这意味着你可以将段落文本换行或将每个句子或短语放在单独的行中。换行符不会出现在输出中。

但是，如果您希望保留段落中的换行符，可以使用空格后跟加号 (`+`) 或在段落上设置 `hardbreaks` 选项。这会导致在每行之后有一个可见的换行符（例如，`<br>`）。

.使用空格后跟加号 (+) 保留换行符
====
 冬天室外很冷， +
 可能会结冰
====

====
冬天室外很冷， +
可能会结冰
====

.使用 `hardbreaks` 选项保留换行符
====
 [%hardbreaks]
 冬天室外很冷，
 可能会结冰
====

====
[%hardbreaks]
冬天室外很冷，
可能会结冰
====

要在整个文档中保留换行符，请将 `hardbreaks` 属性添加到文档的标题中。

.使用 `hardbreaks` 属性在整个文档中保留换行符
====
 = 文档标题
 :hardbreaks:

 冬天室外很冷，
 可能会结冰
====

=== 告诫

有一些语句，你可能想把它们从正文中拿出来，并给它们贴上优先级的标签，以引起人们的注意。这些被称为告诫（admonitions）。它的渲染风格是由指定的标签决定的。Asciidoctor 提供了五种告诫的风格标签。

* `NOTE`
* `TIP`
* `IMPORTANT`
* `CAUTION`
* `WARNING`

.CAUTION 与 WARNING
****
在选择告诫类型时，你可能会发现自己对“注意（caution）”和“警告（warning）”感到困惑，因为这两个词经常互换使用。这里有一个简单的规则可以帮助您区分两者：

* 使用 **CAUTION** 来建议读者谨慎行事（即，小心行事）。
* 使用 **WARNING** 告知读者存在的危险、伤害或后果。

要找到更深入的分析，请参阅link:https://www.differencebetween.com/difference-between-caution-and-vs-warning/[本文]。
****

当你想让人们注意一个单独的段落时，在该段落的第一行开始使用你想使用的标签。该标签必须是大写字母，后面是冒号（`:`）。

.告诫段落语法
====
 WARNING: 这是一条警告信息。
====

注意：

. 标签必须是大写字母并且紧跟一个冒号 (`:`)。
. 用一个空格将段落的第一行与标签分开。

====
WARNING: 这是一条警告信息。
====

告诫段落被呈现在一个呼出框中，其上有告诫标签或其相应的图标，位于沟槽中。图标是通过设置文档上的 `icons` 属性来启用的。

NOTE: 告诫也可以用于封装任何块内容，我们将在后面介绍。

=== 温和的标点符号，强烈的冲击力

就像我们在说话时强调某些单词和短语一样，我们可以在文本中通过用标点符号围绕它们来强调它们。AsciiDoc 把这种标记称为引用文本（quoted text）。

==== 引用文本

例如，在电子邮件中，你可以用星号把一个词括起来，让它“说”得更大声。

 I can't believe it, we *won*!

正如你所期望的那样，星号使文字**变成了**黑体。你几乎可以感觉到这种情绪。这是引用（即格式化）文本的一个例子。

NOTE: 术语“引用”在这里被广泛使用，适用于围绕文本的任何符号，以强调或特殊含义。

以下是 AsciiDoc 识别的引用文本的形式。

.粗体、斜体和等宽格式化语法
====
 对文本使用格式化的时候，如果格式化文本被包含在文本行或者文本中（也就是目标与其他文本或元素相邻），那么你需要同时使用两个符号对其进行文本格式化。例如：我要一个**苹果**、I need Ap**ple**、I need an *Apple*。

 如上，判断目标文本是否处于一种被包含的状态，可以通过检查文本左右两侧是否存在空格来判断。

 AsciiDoc 用 `*` 标注**粗体**，用 `_` 标注__斜体__，用 ` 标注``等宽文本``。

 对于混合格式化，建议从外向内，由等宽、粗体再斜体，依次堆叠符号，如： `*_斜体加粗等宽_*`、`_斜体等宽_`、*_斜体加粗_*
====

====
对文本使用格式化的时候，如果格式化文本被包含在文本行或者文本中（也就是目标与其他文本或元素相邻），那么你需要同时使用两个符号对其进行文本格式化。例如：我要一个**苹果**、I need Ap**ple**、I need an *Apple*。

如上，判断目标文本是否处于一种被包含的状态，可以通过检查文本左右两侧是否存在空格来判断。

AsciiDoc 用 `*` 标注**粗体**，用 `_` 标注__斜体__，用 ` 标注``等宽文本``。

对于混合格式化，建议从外向内，由等宽、粗体再斜体，依次堆叠符号，如： `*_斜体加粗等宽_*`、`_斜体等宽_`、*_斜体加粗_*
====

你可以在任何的引用文本前加上一个属性列表。处于第一位置的属性将被视为一个角色（role）。角色可以被用于对文本应用自定义的样式。

[source,asciidoc]
----
Type the word [.userinput]#asciidoc# into the search bar.
----

当转换为 HTML 时，“asciidoc” 这个词被包裹在 <span> 标签中，并且该角色被用作该元素的 CSS 类。

[source,xml]
----
<span class="userinput">asciidoc</span>
----

你可以使用 CSS 对文本应用样式。

你可能并不总是希望这些替换发生。在这些情况下，你需要使用标记来转移文本。

==== 防止替换

如果你在你不想要的地方触发了引用文本的格式化（文本的样式被替换），你可以使用反斜杠或穿透式宏来阻止它。

Asciidoctor 提供了几种防止替换（substitution）的方法。

.反斜杠
为了防止标点符号被解释为格式化标记，请在它前面加一个反斜杠（`\`）。如果格式化标点符号以两个字符开始（如``__``），你需要在它前面加上两个反斜杠（`\`）。这也是你防止字符和属性引用被替换的方法。当 AsciiDoctor 处理你的文档时，反斜杠会被删除，所以它不会显示在你的输出中。

[source]
----
\*Stars* 将显示为 *Stars*，而不是粗体字。

\&sect; 将显示为实体，而不是 &sect; 符号。

\\__func__ 将显示为 __func__，而不是斜体文本。

\{two-semicolons} 将出现 {two-semicolons}，而不是解析为为;。
----

Asciidoctor 支持几种形式的穿透式宏。

内联传递宏（inline pass macro）::  
一个名为 pass 的内联宏，可用于穿透内容。支持一组可选的替换。
+ 
----
pass:[类似 #{variable} 的内容直接传递给输出]，后面是正常的内容。

仅应用选择替换的内容：pass:c,a[__<{email}>__]
----
单双加号:: 
一种防止文本被格式化的特殊语法。只对符合输出格式的特殊字符进行转义，不支持显式替换。
三加号:: 
用于指定直通内容的特殊语法。不应用任何替换（相当于内联传递宏）并且不支持显式替换。

CAUTION:  Asciidoctor 没有实现块传递宏。相反，你应该使用一个<<pass-blocks,传递块>>。

==== 内联传递宏和显式替换

要从替换中排除短语并禁用特殊字符的转义，请将其包含在内联传递宏中。例如，下面是一种在从 AsciiDoc 生成 HTML 时将文本格式化为下划线的方法：

----
 使用传递宏 pass:[<u>对目标文本</u>] 引用下划线效果。
----

====
使用传递宏 pass:[<u>对目标文本</u>] 引用下划线效果。
====

如果要启用临时引号替换，请将宏值分配给 subs 并使用内联传递宏。

====
 [subs=+macros] <1>
 ----
 这是一段演示文本，包含 *粗体*、_斜体_
 pass:quotes[这是一段包含 *粗体* 的文本。] <2>
 ----
====
<1> macros is assigned to subs, which allows any macros within the block to be processed.
<2> The pass macro is assigned the quotes value. Text within the square brackets will be formatted.

====
[subs=+macros] 
----
这是一段演示文本，包含 *粗体*、_斜体_
pass:quotes[这是一段包含 *粗体* 的文本。] 
----
====

==== 三加号直通

==== 替换

=== 列表

==== 任务清单

==== 有序列表

==== 说明列表

==== 混合列表

=== 链接与图像

==== 外部链接

==== 链接的目标窗口和角色属性

==== 跨文件链接

==== 交叉引用

==== 图像

=== 标题

==== 文档标题

==== 文档属性

==== 章节标题

==== 块标题

== 在 AsciiDoc 中构建块


=== 伪装快

[#pass-blocks]
==== 传递块

== AsciiDoc 还能做什么？

[#converting-your-document]
== 转换文档
