:toc: auto
:doctype: book

== 文档结构

在此页面上，你将了解 AsciiDoc 文档的整体结构。此时不要担心语法的细节。稍后将在文档中详细介绍该主题。现在，我们的目标只是了解 AsciiDoc 文档的组成部分。

=== 文档

AsciiDoc 是一种纯文本书写格式，没有样板附件或序言。一个 AsciiDoc 文档可能只包含一个句子（或者甚至是一个字符）。

以下示例是一个有效的 AsciiDoc 文档，其中一个段落包含一个句子：

----
这是一个基础的 AsciiDoc 文档。
----

当然，你可以拥有比单个句子更多的内容。我们在这里要强调的是，上手很简单。

AsciiDoc 文档是一系列（按行）堆叠在一起的块（block）。这些块通常由空行彼此偏移（尽管在某些情况下这些可能是可选的）。

要将上一个文档从一个段落扩展为两个段落，你可以用一个空行分隔两个段落：

----
这是一个基础的 AsciiDoc 文档。

这个文档包含两个段落。
----

AsciiDoc 文档可能以文档标题（document header）开头。尽管文档标题是可选的，但它经常被使用，因为它允许你指定文档标题并以文档属性的形式设置文档范围的配置和可重用文本。

----
= 文档标题
:reproducible:

这是一个由 {author} 创建的 AsciiDoc 文档。

这个文档有两个段落。
它还有一个标题用来指定文档的标题。
----

几乎任何块的组合都构成了有效的 AsciiDoc 文档（文档类型规定了一些结构要求）。文档的范围可以从单个句子到多部分的书。

=== 文档行

文档行（Line）是 AsciiDoc 中的一个重要结构。一行定义为两边由换行符或文档边界分隔的文本。语法的许多方面必须占据一整行。这就是为什么我们说 AsciiDoc 是一种面向行的语言。

例如，章节标题必须单独占一行。对于属性条目、块标题、块属性列表、块宏、列表项、块定界符等也是如此。

.部分标题示例，必须占一行
----
=== 章节标题
----

.属性条目示例，它也必须至少占据一行
----
:name: value
----

.扩展到两行的属性条目示例
----
:name: value \
more value
----

空行也可能很重要。标题与正文由一个空行分开。许多块也由空行分隔，正如你在前面的两段示例中看到的那样。

相反，段落内容中的行是微不足道的。在学习 AsciiDoc 语法时请牢记这些要点。

=== 块

AsciiDoc 文档中的块（Blocks）奠定了文档结构。一些块可能包含其他块，因此文档结构本质上是分层的（即树结构）。你可以预览此部分结构，例如，通过启用自动目录。块的示例包括段落、章节、列表、分隔块、表格和块宏。

块很容易识别，因为它们通常被空行从其他块分隔（尽管并不总是必需的）。块总是从新的一行开始，在一行的末尾终止，并与左边距对齐。

每个块都可以有一行或多行块元数据。此元数据可以采用块属性、块锚点或块标题的形式。这些元数据行必须位于块本身的上方并与其直接相邻。

章节、非逐字分隔的块和 AsciiDoc 表格单元格可能包含其他块。尽管块形成了层次结构，但即使是嵌套块也从左边距开始。通过要求块从左边距开始，避免了必须跟踪和维护缩进级别的单调乏味，并使内容更可重用。

=== 文本和内联元素

被标记、定界符和元数据线包围着的是文本。文本是文档的主要焦点，也是 AsciiDoc 语法给它这么多空间的原因。文本最常出现在块的行中（例如，段落）、块标题（例如，章节标题）和列表项中，dan当然还可存在于其他地方。

文本可能会被替换。替换（Substitutions）将标记解释为文本格式，用文本或非文本元素替换宏，扩展属性引用，并执行其他类型的文本替换。

除非另有说明，否则普通文本受所有替换的约束。逐字文本（Verbatim text）受最小替换集的约束，以允许它以源码中的样式显示在输出中。也可以禁用所有替换，以便将文本传递到未修改的输出（即原始）。文本的解析最终成为内联元素和其他形式的转换的混合体。

=== 编码和 AsciiDoc 文件

AsciiDoc 文件是具有 `.adoc` 文件扩展名的文本文件（例如，__document.adoc__）。大多数 AsciiDoc 处理器假定文件中的文本使用 UTF-8 编码。 仅当文件以 BOM 开头时才支持 UTF-16 编码。

AsciiDoc 处理器可以从字符串（即字符序列）中处理 AsciiDoc。然而，大多数时候你会将 AsciiDoc 文档保存到一个文件中。