== 块的简介
:toc: auto
:doctype: book

块元素（block element）构成了 AsciiDoc 文档的主要结构，首先是文档本身。

=== 什么是块

块元素（block，又名块）是 AsciiDoc 文档中离散的、面向行的内容块。解析后，该内容块将成为已解析文档模型中的块元素。某些块可能包含其他块，所以我们说块可以嵌套。转换器按文档顺序依次访问每个块，将其转换为相应的输出块。

=== 块的形式

AsciiDoc 语法中块边界的定义方式各不相同。某些块的边界，如列表、段落和块宏，是隐式的。其他块具有使用定界符明确标记的边界（即定界块）。主要的共同点是块总是面向行的。

段落块（paragraph block）被定义为一组离散的连续（非空）行。定界块由定界线界定。章节块（section block，又名章节）由章节标题定义，章节标题以一个或多个等号为前缀。该章节包括章节标题行之后的所有内容，直到下一个同级或父章节标题或文档边界。列表块（list block）由一组同级别的列表项定义的，每个列表项由一个标记表示。说明列表块（Description list block）由一组同级列表项定义，每个列表项由一个或多个术语表示。块宏（block macro）由与块宏语法匹配的单行定义。而且文档也是一个块。

一个块（包括它的元数据行）应该总是被两侧的空行或文档边界所包围。

一个块是否支持嵌套块，取决于块的内容模型（以及语法允许的内容）。

=== 内容模型

块的内容模型（content model）决定了该块可以有什么样的内容（如果有的话），以及如何处理这些内容。AsciiDoc 中的块的内容模型如下：

混合（compound）:: 一个可能只包含其他块的块（例如，章节）
简单（simple）:: 被视为段落文本的连续行的块（并且受正常替换的影响）（例如，段落块）
逐字（verbatim）:: 保存逐字文本的块（“按原样”显示）（并进行逐字替换）（例如，列表块）
原始（raw）:: 一个包含未处理内容的块，该块直接传递到输出而没有应用任何替换（例如，直通块）
空的（empty）:: 没有内容的块（例如，图像块）
表格（table）:: 为强制执行固定结构的表保留的特殊内容模型

内容模型是为所有内置语法推断的（由上下文确定），但可以为自定义块配置。块在不同情况下也可能支持不同的内容模型。情况由上下文和样式决定，在分隔块的情况下，结构容器也是如此。

=== 上下文

你可能经常听到用名称引用的块，例如示例块、侧边栏块、警告块或部分。该名称是块的上下文（context）。

让我们考虑以下正常部分：

====
== 章节标题

章节内容
====

此块的上下文是章节。我们通常将其称为章节（或章节块），使用上下文作为形容词来描述块。在这种情况下，作者不必指定上下文，因为语法隐含了它。

每个块都有一个上下文。上下文通常由语法暗示，但在某些情况下可以显式声明。上下文是将一种块与另一种块区分开来的东西。你可以将上下文视为块的类型。

上下文可以使用块样式进一步修改，以创建一个拥有共同类型的块家族，就像警告块和章节那样。我们很快就会介绍这个修改器。

对于块，上下文有时被称为块名称。在谈论自定义块时，这会经常出现。块名称只是另一层抽象。所有内置块名称都映射到一个上下文。但是块扩展可以将任意块名称映射到一个或多个上下文。最终使用哪个上下文取决于扩展的处理方法返回的内容。最后，上下文决定了块如何转换。

上下文通常决定内容模型。例如，所有章节都隐式具有复合内容模型，因为一个章节可能只包含其他块。所有文字块都隐含地具有逐字内容模型，因为此块的目的是呈现逐字输出。

==== 内置上下文的总结

这是 AsciiDoc 中所有内置块的上下文列表。

NOTE: 在 Asciidoctor API 中，上下文表示为符号（symbols）。在 Ruby 中，符号是一个以冒号为前缀的名称（例如，`:listing`）。本文档有时会在引用上下文名称时使用此表示法。但是，这种表示法并不通用。一些处理器，例如 Asciidoctor.js，将上下文存储为字符串。

.内置上下文
[%autowidth]
|===
|名称|目的

|admonition
|五个警告块之一。

|audio
|音频块

|colist
|标注列表

|dlist
|说明列表

|document
|顶级文档或 AsciiDoc 表格单元格中的文档

|example
|示例块

|floating_title
|离散的标题

|image
|图像块

|list_item
|有序、无序或说明列表中的项目（仅在列表或说明列表块内相关）。在说明列表中，此块用于表示术语和描述。

|listing
|列表块

|literal
|文字块

|olist
|有序列表

|open
|开放块

|page_break
|分页符

|paragraph
|段落

|pass
|直通块

|preamble
|文档的序言

|quote
|引用块

|section
|章节。也可以是部分、章节或特殊部分。

|sidebar
|侧边栏块

|table
|列表块

|table_cell
|表格单元格（仅在表格块内相关）

|thematic_break
|分隔线

|toc
|TOC 块（用于指定自定义 TOC 放置）。

|ulist
|无序列表块

|verse
|诗文块

|video
|视频块

|===

NOTE: 每个内联元素也有一个上下文，但这些元素（还）不能从已解析的文档模型中访问。

你可以通过使用块、块宏或内联宏扩展点来引入其他上下文。

=== 块的样式

=== 块的共性