= AsciiDoc 离线手册
Hanjingxue Boling <bolingh@outlook.com>
v0.2-alpha, 2023-01-17

WARNING: 由于本项目属于下游项目，必然滞后于官方手册的更新进度。有异议的地方以官方手册为准。

CAUTION: AsciiDoc 离线手册处于早期 alpha 阶段，仍有许多内容尚未完善。

== 项目产生的原因

. 虽然 AsciiDoc 的在线文档已经很详尽了。但开发者们并没有提供切实可用的，离线的文档或用户手册。
. AsciiDoc 比 markdown 更为复杂，在不熟悉 AsciiDoc 语法的情况下，时常需要去查阅一下在线文档。
. 将常用的文档和用户手册页翻译，整理成中文，方便我离线使用。

== 如何使用

本文档的绝大部分文件是 AsciiDoc 文档文件，建议使用 link:https://code.visualstudio.com/[VS code] 和 link:https://marketplace.visualstudio.com/items?itemName=asciidoctor.asciidoctor-vscode[AsciiDoc] 阅读本手册。

更多内容另见：link:index.adoc[目录] 或 link:build.adoc[构建索引]。

TIP: 我并不建议使用 GitHub 的在线预览功能浏览本文档，虽然 AsciiDoc 也是 GitHub 支持的标记语言之一，但是有些样式 GitHub 简单的在线预览无法实现，而且部分样例将以源码的形式进行举例。

WARNING: 目前你可以在 link:https://github.com/Hanjingxue-Boling/asciidoc-offline-manual/releases[GitHub Release] 上获取早期测试版本的 EPUB 电子书文件。但此文件目前仅用于预览用途。

== 其他

=== 排版样式

本文采用 link:https://github.com/mzlogin/chinese-copywriting-guidelines[《中文文案排版指北》] 作为排版的参考指南。

=== 许可证

TIP: 详细说明另见 link:license-list.adoc[许可证清单]

本手册页项目基于 link:https://docs.asciidoctor.org/[asciidoc-docs] 进行编写，并对其进行了诸多改动。上游源文件采用 link:https://github.com/asciidoctor/asciidoc-docs/blob/main/LICENSE[CC-BY 4.0] 进行授权使用。

本手册页项目基于 link:https://creativecommons.org/licenses/by-sa/4.0/[CC-BY-SA 4.0] 进行授权分发。